name: Auto-generate project_structure.json

# --- 👇 обязательно ---
permissions:
  contents: write
  actions: read
# ----------------------

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate project_structure.json
        run: python generate_structure.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add project_structure.json
          git commit -m "ci: auto-update project_structure.json" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
